{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-webmvc",
    "version": "6.2.14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-aop",
          "version": {
            "requires": "6.2.14"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.2.14"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "6.2.14"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.2.14"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-expression",
          "version": {
            "requires": "6.2.14"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "6.2.14"
          }
        }
      ],
      "files": [
        {
          "name": "spring-webmvc-6.2.14.jar",
          "url": "spring-webmvc-6.2.14.jar",
          "size": 1092437,
          "sha512": "70acfb36453eb3566f8b85b1ecf2eca5dff67e77f7c1ef9d3b3ed27bf7b6cf229806c889dea6c2dfc593b3d44648a859935256f803ea7f2291a90446894c86bb",
          "sha256": "56ea9178217399f2ddc399c00338152003da6dbf9a75fe0f986ea064613798a1",
          "sha1": "c3f0f0651a4ffe212cbf8389e043a7c20450859c",
          "md5": "b3f9f9adc1efde758dd4bb768099a0bc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-aop",
          "version": {
            "requires": "6.2.14"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.2.14"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "6.2.14"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.2.14"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-expression",
          "version": {
            "requires": "6.2.14"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "6.2.14"
          }
        }
      ],
      "files": [
        {
          "name": "spring-webmvc-6.2.14.jar",
          "url": "spring-webmvc-6.2.14.jar",
          "size": 1092437,
          "sha512": "70acfb36453eb3566f8b85b1ecf2eca5dff67e77f7c1ef9d3b3ed27bf7b6cf229806c889dea6c2dfc593b3d44648a859935256f803ea7f2291a90446894c86bb",
          "sha256": "56ea9178217399f2ddc399c00338152003da6dbf9a75fe0f986ea064613798a1",
          "sha1": "c3f0f0651a4ffe212cbf8389e043a7c20450859c",
          "md5": "b3f9f9adc1efde758dd4bb768099a0bc"
        }
      ]
    }
  ]
}
