{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-aop",
    "version": "6.2.14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.2.14"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.2.14"
          }
        }
      ],
      "files": [
        {
          "name": "spring-aop-6.2.14.jar",
          "url": "spring-aop-6.2.14.jar",
          "size": 420267,
          "sha512": "4403cb311a8b504a9e0ea0b6c57040bd477b4ea448248122b758ffa60227f532bb132769be4f4bf2ac1a6aaef5c45e56e3dc7ebc86ff0c9bbb55883aed3349d7",
          "sha256": "8196d9765c73d1cc81d83d40937dbd78763ef0c3f71f0cdade252d0b9db99157",
          "sha1": "9928bf6218013fc04292bd2bb37a0099d7582e97",
          "md5": "2b6adef82e05545c58496429d7b75655"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.2.14"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.2.14"
          }
        }
      ],
      "files": [
        {
          "name": "spring-aop-6.2.14.jar",
          "url": "spring-aop-6.2.14.jar",
          "size": 420267,
          "sha512": "4403cb311a8b504a9e0ea0b6c57040bd477b4ea448248122b758ffa60227f532bb132769be4f4bf2ac1a6aaef5c45e56e3dc7ebc86ff0c9bbb55883aed3349d7",
          "sha256": "8196d9765c73d1cc81d83d40937dbd78763ef0c3f71f0cdade252d0b9db99157",
          "sha1": "9928bf6218013fc04292bd2bb37a0099d7582e97",
          "md5": "2b6adef82e05545c58496429d7b75655"
        }
      ]
    }
  ]
}
