{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.security",
    "module": "spring-security-test",
    "version": "6.5.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.security",
          "module": "spring-security-core",
          "version": {
            "requires": "6.5.7"
          }
        },
        {
          "group": "org.springframework.security",
          "module": "spring-security-web",
          "version": {
            "requires": "6.5.7"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.2.13"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-test",
          "version": {
            "requires": "6.2.13"
          }
        }
      ],
      "files": [
        {
          "name": "spring-security-test-6.5.7.jar",
          "url": "spring-security-test-6.5.7.jar",
          "size": 136115,
          "sha512": "12a0d69a99be0df1be619d6b12bc1f96a7d29a5032dab7a21bb79a98e97799788be2c8154e535751d6157f814ef97879b568a389f93aa9b1d931e72f11e82b71",
          "sha256": "e5e1281cffc0b942406d3c21113bcd3023e9ffcfb4986b08692e4e03f4df21e8",
          "sha1": "67cb9ab3bee3cb26adac40fd3aee79ff391459e5",
          "md5": "60ea55622efcdced16cfb56c60b0d81b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.security",
          "module": "spring-security-core",
          "version": {
            "requires": "6.5.7"
          }
        },
        {
          "group": "org.springframework.security",
          "module": "spring-security-web",
          "version": {
            "requires": "6.5.7"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.2.13"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-test",
          "version": {
            "requires": "6.2.13"
          }
        }
      ],
      "files": [
        {
          "name": "spring-security-test-6.5.7.jar",
          "url": "spring-security-test-6.5.7.jar",
          "size": 136115,
          "sha512": "12a0d69a99be0df1be619d6b12bc1f96a7d29a5032dab7a21bb79a98e97799788be2c8154e535751d6157f814ef97879b568a389f93aa9b1d931e72f11e82b71",
          "sha256": "e5e1281cffc0b942406d3c21113bcd3023e9ffcfb4986b08692e4e03f4df21e8",
          "sha1": "67cb9ab3bee3cb26adac40fd3aee79ff391459e5",
          "md5": "60ea55622efcdced16cfb56c60b0d81b"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-security-test-6.5.7-javadoc.jar",
          "url": "spring-security-test-6.5.7-javadoc.jar",
          "size": 236711,
          "sha512": "5a9d9b79f3dc49f39db5aa8047cbff999299eb61e55ede0080989291977e8607614595855d421d664f7728b2975ba915f6d4c9f9d1b71a35f5251c85e954069c",
          "sha256": "71f5c6ceabeeeed955f3ab2a87e6361fa48c26b119b9b0e4902b62f6dbd3f914",
          "sha1": "62587916396dfe09dc7050bd625ec2da47130107",
          "md5": "c753131a41cb456547d13437a53bd827"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-security-test-6.5.7-sources.jar",
          "url": "spring-security-test-6.5.7-sources.jar",
          "size": 60552,
          "sha512": "7461e0b5130c25557cc848131d3b4fb4bc3ca2e61a5e22e301ec01e1c9c04f1ce386dd7d70d0b48271ee747528e9616ef14aef1df509b8c840127e22d17e150d",
          "sha256": "329c2d8104c7d06f53d14c05a67be2d0fe437c01374fcf1886f95835a06a39de",
          "sha1": "94cb6fa4b474bec38b1d18c1f28097f4ed0d4a9a",
          "md5": "a2018faad97dedc925a4d986e33d72ff"
        }
      ]
    }
  ]
}
